
export const SUPPORTED_LANGUAGES = [
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "typescript", label: "TypeScript" },
  { value: "csharp", label: "C#" },
  { value: "cpp", label: "C++" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "go", label: "Go" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "rust", label: "Rust" },
  { value: "scala", label: "Scala" },
  { value: "perl", label: "Perl" },
  { value: "lua", label: "Lua" },
  { value: "haskell", label: "Haskell" },
  { value: "elixir", label: "Elixir" },
  { value: "clojure", label: "Clojure" },
  { value: "dart", label: "Dart" },
  { value: "r", label: "R" },
  { value: "matlab", label: "MATLAB" },
  { value: "sql", label: "SQL" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "shell", label: "Shell Script" },
  { value: "powershell", label: "PowerShell" },
  { value: "objectivec", label: "Objective-C" },
  { value: "groovy", label: "Groovy" },
  { value: "pascal", label: "Pascal" },
  { value: "fortran", label: "Fortran" },
  { value: "assembly", label: "Assembly" },
  { value: "lisp", label: "Lisp" },
  { value: "prolog", label: "Prolog" },
  { value: "ada", label: "Ada" },
  { value: "cobol", label: "COBOL" },
  { value: "scheme", label: "Scheme" },
  { value: "erlang", label: "Erlang" },
  { value: "fsharp", label: "F#" },
  { value: "ocaml", label: "OCaml" },
  { value: "julia", label: "Julia" },
  { value: "nim", label: "Nim" },
  { value: "crystal", label: "Crystal" },
  { value: "zig", label: "Zig" },
  { value: "solidity", label: "Solidity" },
  { value: "vyper", label: "Vyper" },
  { value: "haxe", label: "Haxe" },
  { value: "coffeescript", label: "CoffeeScript" },
  { value: "vbnet", label: "VB.NET" },
  { value: "apex", label: "Apex" },
  { value: "sas", label: "SAS" },
  { value: "d", label: "D" },
];

export const DEFAULT_LANGUAGE = SUPPORTED_LANGUAGES[0].value;
